### PR TITLE
Make reference subcarrier decoding more robust

### LINKED ISSUE #318: With weak signals, The logged primary service mode may be incorrect.
With https://github.com/theori-io/nrsc5/pull/301 it appears when weak signals present, The logged primary service mode may be incorrect. 

Here is a log trying to decode a very weak signal with rapid fading/picket fencing in a moving car. You can see that it's reporting values that can't possibly exist. 

> Block @ 24
> Block @ 0
> Block @ 0
> Block @ 0
> 22:36:38 Synchronized
> Primary service mode: 1
> 22:36:38 MER: -9.8 dB (lower), -10.1 dB (upper)
> 22:36:38 BER: 0.197532, avg: 0.197532, min: 0.197532, max: 0.197532
> 22:36:38 Lost synchronization
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 1
> Block @ 0
> Block @ 0
> Block @ 0
> 22:36:39 Synchronized
> Primary service mode: 1
> 22:36:39 MER: -8.6 dB (lower), -8.4 dB (upper)
> 22:36:39 BER: 0.197844, avg: 0.197688, min: 0.197532, max: 0.197844
> 22:36:39 Lost synchronization
> Block @ 0
> Block @ 0
> Block @ 0
> 22:36:40 Synchronized
> Primary service mode: 25
> 22:36:40 MER: -10.4 dB (lower), -13.8 dB (upper)
> 22:36:40 BER: 0.172855, avg: 0.189410, min: 0.172855, max: 0.197844
> 22:36:40 Lost synchronization
> CFO: 363.372803 Hz
> Block @ 26
> Block @ 0
> 22:36:44 Synchronized
> Primary service mode: 1
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 MER: -12.3 dB (lower), -7.7 dB (upper)
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 Audio program 0: public, type: None, sound experience 0
> 22:36:44 Audio program 1: public, type: None, sound experience 0
> 22:36:44 BER: 0.184348, avg: 0.188144, min: 0.172855, max: 0.197844
> 22:36:44 Lost synchronization
> Block @ 0
> Block @ 0
> 22:36:44 Synchronized
> Primary service mode: 1
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 Station name: KVVF
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 Station name: KVVF
> 22:36:44 Audio program 0: public, type: None, sound experience 0
> 22:36:44 Audio program 1: public, type: None, sound experience 0
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 Station name: KVVF
> 22:36:44 Slogan: HD1
> 22:36:44 Audio program 0: public, type: None, sound experience 0
> 22:36:44 Audio program 1: public, type: None, sound experience 0
> 22:36:44 Country: US, FCC facility ID: 19532
> 22:36:44 Station name: KVVF
> 22:36:44 Slogan: HD1
> 22:36:44 Station location: 39.185303, -76.806274, 96m
> 22:36:44 Audio program 0: public, type: None, sound experience 0
> 22:36:44 Audio program 1: public, type: None, sound experience 0
> 22:36:44 MER: -1.3 dB (lower), 3.4 dB (upper)
> 22:36:44 BER: 0.089872, avg: 0.168490, min: 0.089872, max: 0.197844
> RS corrected 2 symbols
> 22:36:44 Title: La Bebe (Remix)
> 22:36:44 Artist: YNG LVCAS & Peso Pluma
> crc mismatch!
> ignoring partial pdu
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> psd crc mismatch
> ignoring partial pdu
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> crc mismatch!
> 22:36:44 MER: -10.0 dB (lower), -0.8 dB (upper)
> 22:36:44 BER: 0.226445, avg: 0.178149, min: 0.089872, max: 0.226445
> 22:36:44 Lost synchronization
> Block @ 1
> Block @ 0
> 22:36:45 Synchronized
> Primary service mode: 31
> Local time zone offset: -480 minutes, DST sched. 1, local DST? no, regional DST? no
> 22:36:45 Country: US, FCC facility ID: 19532
> 22:36:45 MER: -12.0 dB (lower), -9.7 dB (upper)
> 22:36:45 BER: 0.176869, avg: 0.177966, min: 0.089872, max: 0.226445
> 22:36:45 Lost synchronization
> Block @ 0
> Block @ 0
> Block @ 0
> 22:36:45 Synchronized
> Primary service mode: 1
> 22:36:45 Country: US, FCC facility ID: 19532
> 22:36:45 Station name: KVVF
> 22:36:45 Country: US, FCC facility ID: 19532
> 22:36:45 Station name: KVVF
> 22:36:45 Slogan: HD1
> 22:36:45 Country: US, FCC facility ID: 19532
> 22:36:45 Station name: KVVF
> 22:36:45 Slogan: HD1
> 22:36:45 Audio program 0: public, type: None, sound experience 0
> 22:36:45 Audio program 1: public, type: None, sound experience 0
> 22:36:45 MER: -7.1 dB (lower), -3.2 dB (upper)
> 22:36:45 BER: 0.201409, avg: 0.180897, min: 0.089872, max: 0.226445
> 22:36:45 Lost synchronization
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 0
> Block @ 30
> Block @ 0
> Block @ 0
> Block @ 0
> 22:36:48 Synchronized
> Primary service mode: 1
> 22:36:48 Country: US, FCC facility ID: 19532
> 22:36:48 Station name: KVVF
> 22:36:48 Country: US, FCC facility ID: 19532
> 22:36:48 Station name: KVVF
> 22:36:48 Audio program 0: public, type: None, sound experience 0
> 22:36:48 Audio program 1: public, type: None, sound experience 0
> 22:36:48 Country: US, FCC facility ID: 19532
> 22:36:48 Station name: KVVF
> 22:36:48 Station location: 39.185303, -76.806274, 96m
> 22:36:48 Audio program 0: public, type: None, sound experience 0
> 22:36:48 Audio program 1: public, type: None, sound experience 0
> 22:36:48 Country: US, FCC facility ID: 19532
> 22:36:48 Station name: KVVF
> 22:36:48 Slogan: HD1
> 22:36:48 Station location: 39.185303, -76.806274, 96m
> 22:36:48 Audio program 0: public, type: None, sound experience 0
> 22:36:48 Audio program 1: public, type: None, sound experience 0
> 22:36:48 MER: -5.3 dB (lower), -7.8 dB (upper)
> 22:36:48 BER: 0.124743, avg: 0.174657, min: 0.089872, max: 0.226445
> 22:36:48 Lost synchronization

### PR DESCRIPTION
**Pull request by argilo**
Fixes #318.

Reference subcarriers are mainly used for synchronization, but they also convey some important data fields (L1 block count, primary service mode, advanced service mode, secondary channel indicator). Because the data fields are not protected by FEC, errors can creep in, especially when SNR is low.

To ensure correct decoding of the block count value, nrsc5 requires the value to agree across several reference subcarriers. But there is no such check for the primary service mode, and the decoded value is prone to corruption. I've added a check here, and the primary service mode is now decoded correctly for all my I/Q recordings. The total number of decoded audio packets also increased by 0.23%.

Also, the `decode_ref_fm` function now returns the block count value, instead of requiring it to be zero. This change opens up the possibility of starting PIDS decoding earlier (#380), which I'll tackle in a future PR.

### CODE REVIEW

File: src/sync.c [hunk 1]
```diff
@@ -95,9 +95,10 @@ static void adjust_ref(sync_t *st, unsigned int ref, int cfo)
     unsigned int n;
     float cfo_freq = 2 * M_PI * cfo * CP_FM / FFT_FM;
 
-    // sync bits (after DBPSK)
+    // differentially-encoded sync & parity bits
     static const signed char sync[] = {
-        -1, 1, -1, -1, -1, 1, 1
+        -1, 1, -1, -1, -1, 1, 1, 0, 1, -1, 0, 0, 0, -1, -1, 0,
+        0, 0, 0, 0, -1, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1
```
Comment (argilo) [inline src/sync.c:101]: Instead of checking only the first seven sync bits here, I added the remaining sync bits, as well as the parity bits (which are fixed after differential encoding).

File: src/sync.c [hunk 2]
```diff
@@ -170,29 +169,43 @@ static int fuzzy_match(const signed char *needle, unsigned int needle_size, cons
...
+    return 0;    
 }
 
-static int find_ref(sync_t *st, unsigned int ref, unsigned int rsid)
+static int find_ref_fm(sync_t *st, unsigned int ref, unsigned int rsid)
 {
     signed char needle[] = {
-        0, 1, 1, 0, 0, 1, 0, -1, -1, 1, rsid >> 1, rsid & 1, 0, (rsid >> 1) ^ (rsid & 1), 0, -1, -1, -1, -1, -1, -1, 1, 1, 1
+        0, 1, 0, 0, 0, 1, 1, -1, 1, 0, rsid >> 1, (rsid >> 1) ^ (rsid & 1), -1, 0, 0, -1,
+        -1, -1, -1, -1, 0, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, 0
```
Comment (argilo) [inline src/sync.c:195]: Searching the differentially-encoded bits is simpler, so I've changed to that approach here.

The only downside is that we have to search twice, since there is a 180-degree phase ambiguity at this point. (The ambiguity goes away once the start of a block is found.)
